# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/tasarim.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.sol_menu_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sol_menu_frame.sizePolicy().hasHeightForWidth())
        self.sol_menu_frame.setSizePolicy(sizePolicy)
        self.sol_menu_frame.setMinimumSize(QtCore.QSize(120, 1080))
        self.sol_menu_frame.setMaximumSize(QtCore.QSize(120, 1080))
        self.sol_menu_frame.setStyleSheet("border: none;\n"
"background-color: #1A1A24;background-color: #1A1A24; min-width: 120px; max-width: 120px;")
        self.sol_menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sol_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sol_menu_frame.setObjectName("sol_menu_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.sol_menu_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem)
        self.home_button = QtWidgets.QPushButton(self.sol_menu_frame)
        self.home_button.setMinimumSize(QtCore.QSize(148, 64))
        self.home_button.setMaximumSize(QtCore.QSize(148, 64))
        self.home_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;        /* 1. İçeriği sola yasla */\n"
"    padding-left: 28px;      /* 2. Soldan 30px boşluk bırak (Figma\'daki değerini buraya yaz) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2D2D44;\n"
"    border-left: 4px solid #00E5FF;\n"
"    /* Mavi çizgi sola yapışsın diye sol paddingi koruyoruz ama border ekliyoruz */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #00E5FF;\n"
"}")
        self.home_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ikonlar/resimler/ana menü 1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_button.setIcon(icon)
        self.home_button.setIconSize(QtCore.QSize(64, 64))
        self.home_button.setObjectName("home_button")
        self.verticalLayout_8.addWidget(self.home_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.kamera_button = QtWidgets.QPushButton(self.sol_menu_frame)
        self.kamera_button.setMinimumSize(QtCore.QSize(148, 64))
        self.kamera_button.setMaximumSize(QtCore.QSize(148, 64))
        self.kamera_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;        /* 1. İçeriği sola yasla */\n"
"    padding-left: 28px;      /* 2. Soldan 30px boşluk bırak (Figma\'daki değerini buraya yaz) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2D2D44;\n"
"    border-left: 4px solid #00E5FF;\n"
"    /* Mavi çizgi sola yapışsın diye sol paddingi koruyoruz ama border ekliyoruz */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #00E5FF;\n"
"}")
        self.kamera_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ikonlar/resimler/video-camera 1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kamera_button.setIcon(icon1)
        self.kamera_button.setIconSize(QtCore.QSize(64, 64))
        self.kamera_button.setObjectName("kamera_button")
        self.verticalLayout_8.addWidget(self.kamera_button)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem2)
        self.navigasyon_button = QtWidgets.QPushButton(self.sol_menu_frame)
        self.navigasyon_button.setMinimumSize(QtCore.QSize(141, 64))
        self.navigasyon_button.setMaximumSize(QtCore.QSize(141, 64))
        self.navigasyon_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;        /* 1. İçeriği sola yasla */\n"
"    padding-left: 21px;      /* 2. Soldan 30px boşluk bırak (Figma\'daki değerini buraya yaz) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2D2D44;\n"
"    border-left: 4px solid #00E5FF;\n"
"    /* Mavi çizgi sola yapışsın diye sol paddingi koruyoruz ama border ekliyoruz */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #00E5FF;\n"
"}")
        self.navigasyon_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ikonlar/resimler/gps 1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.navigasyon_button.setIcon(icon2)
        self.navigasyon_button.setIconSize(QtCore.QSize(80, 80))
        self.navigasyon_button.setObjectName("navigasyon_button")
        self.verticalLayout_8.addWidget(self.navigasyon_button)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem3)
        self.hakkinda_button = QtWidgets.QPushButton(self.sol_menu_frame)
        self.hakkinda_button.setMinimumSize(QtCore.QSize(144, 64))
        self.hakkinda_button.setMaximumSize(QtCore.QSize(144, 64))
        self.hakkinda_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;        /* 1. İçeriği sola yasla */\n"
"    padding-left: 24px;      /* 2. Soldan 30px boşluk bırak (Figma\'daki değerini buraya yaz) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2D2D44;\n"
"    border-left: 4px solid #00E5FF;\n"
"    /* Mavi çizgi sola yapışsın diye sol paddingi koruyoruz ama border ekliyoruz */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #00E5FF;\n"
"}")
        self.hakkinda_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ikonlar/resimler/help 1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hakkinda_button.setIcon(icon3)
        self.hakkinda_button.setIconSize(QtCore.QSize(72, 72))
        self.hakkinda_button.setObjectName("hakkinda_button")
        self.verticalLayout_8.addWidget(self.hakkinda_button)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem4)
        self.ayarlar_button = QtWidgets.QPushButton(self.sol_menu_frame)
        self.ayarlar_button.setMinimumSize(QtCore.QSize(148, 64))
        self.ayarlar_button.setMaximumSize(QtCore.QSize(148, 64))
        self.ayarlar_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;        /* 1. İçeriği sola yasla */\n"
"    padding-left: 28px;      /* 2. Soldan 30px boşluk bırak (Figma\'daki değerini buraya yaz) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2D2D44;\n"
"    border-left: 4px solid #00E5FF;\n"
"    /* Mavi çizgi sola yapışsın diye sol paddingi koruyoruz ama border ekliyoruz */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #00E5FF;\n"
"}")
        self.ayarlar_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ikonlar/resimler/settings 1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ayarlar_button.setIcon(icon4)
        self.ayarlar_button.setIconSize(QtCore.QSize(64, 64))
        self.ayarlar_button.setObjectName("ayarlar_button")
        self.verticalLayout_8.addWidget(self.ayarlar_button)
        spacerItem5 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        self.pushButton_acilKapat = QtWidgets.QPushButton(self.sol_menu_frame)
        self.pushButton_acilKapat.setMinimumSize(QtCore.QSize(148, 72))
        self.pushButton_acilKapat.setMaximumSize(QtCore.QSize(148, 72))
        self.pushButton_acilKapat.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;        /* 1. İçeriği sola yasla */\n"
"    padding-left: 28px;      /* 2. Soldan 30px boşluk bırak (Figma\'daki değerini buraya yaz) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2D2D44;\n"
"    border-left: 4px solid #CC0000;\n"
"    /* Mavi çizgi sola yapışsın diye sol paddingi koruyoruz ama border ekliyoruz */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #00E5FF;\n"
"}")
        self.pushButton_acilKapat.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ikonlar/resimler/lightning-slash-fill-svgrepo-com 1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_acilKapat.setIcon(icon5)
        self.pushButton_acilKapat.setIconSize(QtCore.QSize(72, 72))
        self.pushButton_acilKapat.setObjectName("pushButton_acilKapat")
        self.verticalLayout_8.addWidget(self.pushButton_acilKapat)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem6)
        self.power_button = QtWidgets.QPushButton(self.sol_menu_frame)
        self.power_button.setMinimumSize(QtCore.QSize(148, 64))
        self.power_button.setMaximumSize(QtCore.QSize(148, 64))
        self.power_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;        /* 1. İçeriği sola yasla */\n"
"    padding-left: 28px;      /* 2. Soldan 30px boşluk bırak (Figma\'daki değerini buraya yaz) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2D2D44;\n"
"    border-left: 4px solid #00E5FF;\n"
"    /* Mavi çizgi sola yapışsın diye sol paddingi koruyoruz ama border ekliyoruz */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #00E5FF;\n"
"}")
        self.power_button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/ikonlar/resimler/power 1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.power_button.setIcon(icon6)
        self.power_button.setIconSize(QtCore.QSize(64, 64))
        self.power_button.setObjectName("power_button")
        self.verticalLayout_8.addWidget(self.power_button)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.verticalLayout_8)
        self.gridLayout.addWidget(self.sol_menu_frame, 0, 0, 1, 1)
        self.icerik_frame = QtWidgets.QFrame(self.centralwidget)
        self.icerik_frame.setStyleSheet("background-color: #111116;")
        self.icerik_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.icerik_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.icerik_frame.setObjectName("icerik_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.icerik_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.icerik_frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_anaMenu = QtWidgets.QWidget()
        self.page_anaMenu.setObjectName("page_anaMenu")
        self.label_baslik = QtWidgets.QLabel(self.page_anaMenu)
        self.label_baslik.setGeometry(QtCore.QRect(0, 40, 1781, 71))
        self.label_baslik.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;            /* Beyaz Yazı */\n"
"    font-family: \"Roboto Mono\"; /* İstediğin Font */\n"
"    font-size: 48px;           /* İstediğin Dev Punto */\n"
"    font-weight: bold;         /* Kalın */\n"
"    letter-spacing: 15px;       /* Harf aralığı (48 puntoda çok açılmasın diye 5px idealdir) */\n"
"    background-color: transparent;\n"
"}")
        self.label_baslik.setAlignment(QtCore.Qt.AlignCenter)
        self.label_baslik.setObjectName("label_baslik")
        self.frame_merkezAlan = QtWidgets.QFrame(self.page_anaMenu)
        self.frame_merkezAlan.setGeometry(QtCore.QRect(110, 150, 1621, 511))
        self.frame_merkezAlan.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.frame_merkezAlan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_merkezAlan.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_merkezAlan.setObjectName("frame_merkezAlan")
        self.frame_halka = QtWidgets.QFrame(self.frame_merkezAlan)
        self.frame_halka.setGeometry(QtCore.QRect(530, 100, 400, 400))
        self.frame_halka.setStyleSheet("QFrame#frame_halka {\n"
"    background-color: rgba(0, 0, 0, 50); /* Hafif siyah zemin */\n"
"    border-radius: 175px;                /* Yarıçap (350/2) -> Tam Yuvarlak */\n"
"}")
        self.frame_halka.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_halka.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_halka.setObjectName("frame_halka")
        self.label_radar_cember = QtWidgets.QLabel(self.frame_halka)
        self.label_radar_cember.setGeometry(QtCore.QRect(0, 0, 380, 380))
        self.label_radar_cember.setObjectName("label_radar_cember")
        self.label_sistemLogo = QtWidgets.QLabel(self.frame_merkezAlan)
        self.label_sistemLogo.setGeometry(QtCore.QRect(655, 160, 141, 131))
        self.label_sistemLogo.setText("")
        self.label_sistemLogo.setPixmap(QtGui.QPixmap(":/ikonlar/resimler/tufan logo 1.png"))
        self.label_sistemLogo.setScaledContents(True)
        self.label_sistemLogo.setObjectName("label_sistemLogo")
        self.label_sistemYazi = QtWidgets.QLabel(self.frame_merkezAlan)
        self.label_sistemYazi.setGeometry(QtCore.QRect(540, 330, 371, 81))
        self.label_sistemYazi.setStyleSheet("color: #00FF00;      /* Parlak Yeşil */\n"
"font-size: 32px;     /* Okunaklı Boyut */\n"
"font-weight: bold;   /* Kalın */\n"
"font-family: \"Roboto Mono\";\n"
"background-color: transparent;")
        self.label_sistemYazi.setTextFormat(QtCore.Qt.PlainText)
        self.label_sistemYazi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sistemYazi.setObjectName("label_sistemYazi")
        self.layoutWidget = QtWidgets.QWidget(self.frame_merkezAlan)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 150, 1428, 276))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(480)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(40)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_motorlar = QtWidgets.QFrame(self.layoutWidget)
        self.frame_motorlar.setMinimumSize(QtCore.QSize(471, 64))
        self.frame_motorlar.setStyleSheet("QFrame#frame_motorlar{\n"
"    background-color: rgba(20, 30, 40, 180); /* Arkası hafif görünen koyu zemin */\n"
"    border: 1px solid #444455;               /* İnce gri metalik çerçeve */\n"
"    border-radius: 24px;                     /* Köşeleri tam yuvarla (50px yüksekliğin yarısı) */\n"
"}")
        self.frame_motorlar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_motorlar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_motorlar.setObjectName("frame_motorlar")
        self.label_motorYazi = QtWidgets.QLabel(self.frame_motorlar)
        self.label_motorYazi.setGeometry(QtCore.QRect(10, 16, 451, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_motorYazi.sizePolicy().hasHeightForWidth())
        self.label_motorYazi.setSizePolicy(sizePolicy)
        self.label_motorYazi.setMinimumSize(QtCore.QSize(100, 0))
        self.label_motorYazi.setStyleSheet("color: #00FF00;      /* Parlak Yeşil */\n"
"font-weight: bold;   /* Kalın */\n"
"font-size: 24px;     /* Okunaklı Boyut */\n"
"border: none;        /* Label\'ın kendi çerçevesi olmasın */\n"
"background-color: transparent;")
        self.label_motorYazi.setTextFormat(QtCore.Qt.PlainText)
        self.label_motorYazi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motorYazi.setObjectName("label_motorYazi")
        self.verticalLayout_6.addWidget(self.frame_motorlar)
        self.frame_Guc = QtWidgets.QFrame(self.layoutWidget)
        self.frame_Guc.setMinimumSize(QtCore.QSize(471, 64))
        self.frame_Guc.setStyleSheet("QFrame#frame_Guc{\n"
"    background-color: rgba(20, 30, 40, 180); /* Arkası hafif görünen koyu zemin */\n"
"    border: 1px solid #444455;               /* İnce gri metalik çerçeve */\n"
"    border-radius: 24px;                     /* Köşeleri tam yuvarla (50px yüksekliğin yarısı) */\n"
"}")
        self.frame_Guc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Guc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Guc.setObjectName("frame_Guc")
        self.label_GucYazi = QtWidgets.QLabel(self.frame_Guc)
        self.label_GucYazi.setGeometry(QtCore.QRect(10, 17, 451, 31))
        self.label_GucYazi.setStyleSheet("color: #00FF00;      /* Parlak Yeşil */\n"
"font-weight: bold;   /* Kalın */\n"
"font-size: 20px;     /* Okunaklı Boyut */\n"
"border: none;        /* Label\'ın kendi çerçevesi olmasın */\n"
"background-color: transparent;")
        self.label_GucYazi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GucYazi.setObjectName("label_GucYazi")
        self.verticalLayout_6.addWidget(self.frame_Guc)
        self.frame_lidar = QtWidgets.QFrame(self.layoutWidget)
        self.frame_lidar.setMinimumSize(QtCore.QSize(471, 64))
        self.frame_lidar.setStyleSheet("QFrame#frame_lidar{\n"
"    background-color: rgba(20, 30, 40, 180); /* Arkası hafif görünen koyu zemin */\n"
"    border: 1px solid #444455;               /* İnce gri metalik çerçeve */\n"
"    border-radius: 24px;                     /* Köşeleri tam yuvarla (50px yüksekliğin yarısı) */\n"
"}")
        self.frame_lidar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lidar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lidar.setObjectName("frame_lidar")
        self.label_lidarYazi = QtWidgets.QLabel(self.frame_lidar)
        self.label_lidarYazi.setGeometry(QtCore.QRect(15, 17, 441, 31))
        self.label_lidarYazi.setStyleSheet("color: #00AAFF;      /* Parlak Yeşil */\n"
"font-weight: bold;   /* Kalın */\n"
"font-size: 24px;     /* Okunaklı Boyut */\n"
"border: none;        /* Label\'ın kendi çerçevesi olmasın */\n"
"background-color: transparent;")
        self.label_lidarYazi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lidarYazi.setObjectName("label_lidarYazi")
        self.verticalLayout_6.addWidget(self.frame_lidar)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(40)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_wifi = QtWidgets.QFrame(self.layoutWidget)
        self.frame_wifi.setMinimumSize(QtCore.QSize(471, 64))
        self.frame_wifi.setStyleSheet("QFrame#frame_wifi{\n"
"    background-color: rgba(20, 30, 40, 180); /* Arkası hafif görünen koyu zemin */\n"
"    border: 1px solid #444455;               /* İnce gri metalik çerçeve */\n"
"    border-radius: 24px;                     /* Köşeleri tam yuvarla (50px yüksekliğin yarısı) */\n"
"}")
        self.frame_wifi.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_wifi.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_wifi.setObjectName("frame_wifi")
        self.label_wifiYazi = QtWidgets.QLabel(self.frame_wifi)
        self.label_wifiYazi.setGeometry(QtCore.QRect(10, 17, 451, 31))
        self.label_wifiYazi.setStyleSheet("color: #00FF00;      /* Parlak Yeşil */\n"
"font-weight: bold;   /* Kalın */\n"
"font-size: 24px;     /* Okunaklı Boyut */\n"
"border: none;        /* Label\'ın kendi çerçevesi olmasın */\n"
"background-color: transparent;")
        self.label_wifiYazi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_wifiYazi.setObjectName("label_wifiYazi")
        self.verticalLayout_7.addWidget(self.frame_wifi)
        self.frame_GPS = QtWidgets.QFrame(self.layoutWidget)
        self.frame_GPS.setMinimumSize(QtCore.QSize(471, 64))
        self.frame_GPS.setStyleSheet("QFrame#frame_GPS{\n"
"    background-color: rgba(20, 30, 40, 180); /* Arkası hafif görünen koyu zemin */\n"
"    border: 1px solid #444455;               /* İnce gri metalik çerçeve */\n"
"    border-radius: 24px;                     /* Köşeleri tam yuvarla (50px yüksekliğin yarısı) */\n"
"}")
        self.frame_GPS.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_GPS.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_GPS.setObjectName("frame_GPS")
        self.label_gpsYazi = QtWidgets.QLabel(self.frame_GPS)
        self.label_gpsYazi.setGeometry(QtCore.QRect(10, 17, 451, 31))
        self.label_gpsYazi.setStyleSheet("color: #00FF00;      /* Parlak Yeşil */\n"
"font-weight: bold;   /* Kalın */\n"
"font-size: 24px;     /* Okunaklı Boyut */\n"
"border: none;        /* Label\'ın kendi çerçevesi olmasın */\n"
"background-color: transparent;")
        self.label_gpsYazi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gpsYazi.setObjectName("label_gpsYazi")
        self.verticalLayout_7.addWidget(self.frame_GPS)
        self.frame_kamera = QtWidgets.QFrame(self.layoutWidget)
        self.frame_kamera.setMinimumSize(QtCore.QSize(471, 64))
        self.frame_kamera.setStyleSheet("QFrame#frame_kamera{\n"
"    background-color: rgba(20, 30, 40, 180); /* Arkası hafif görünen koyu zemin */\n"
"    border: 1px solid #444455;               /* İnce gri metalik çerçeve */\n"
"    border-radius: 24px;                     /* Köşeleri tam yuvarla (50px yüksekliğin yarısı) */\n"
"}")
        self.frame_kamera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_kamera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_kamera.setObjectName("frame_kamera")
        self.label_kameraYazi = QtWidgets.QLabel(self.frame_kamera)
        self.label_kameraYazi.setGeometry(QtCore.QRect(10, 17, 451, 31))
        self.label_kameraYazi.setStyleSheet("color: #00FF00;      /* Parlak Yeşil */\n"
"font-weight: bold;   /* Kalın */\n"
"font-size: 24px;     /* Okunaklı Boyut */\n"
"border: none;        /* Label\'ın kendi çerçevesi olmasın */\n"
"background-color: transparent;")
        self.label_kameraYazi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kameraYazi.setObjectName("label_kameraYazi")
        self.verticalLayout_7.addWidget(self.frame_kamera)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.pushButton_KAYIT = QtWidgets.QPushButton(self.page_anaMenu)
        self.pushButton_KAYIT.setGeometry(QtCore.QRect(1450, 670, 280, 80))
        self.pushButton_KAYIT.setStyleSheet("/* --- Normal Durum --- */\n"
"QPushButton#pushButton_KAYIT {\n"
"    background-color: #252530;  /* Koyu Gri Zemin */\n"
"    color: white;               /* Beyaz Yazı */\n"
"    border: 2px solid #555;     /* Biraz daha kalın çerçeve */\n"
"    border-radius: 24px;        /* Daha yuvarlak köşeler */\n"
"    \n"
"    font-weight: bold;          /* Kalın Yazı */\n"
"    font-size: 24px;            /* <--- İŞTE YAZIYI BÜYÜTEN KISIM (16 veya 18 dene) */\n"
"    font-family: \"Roboto Mono\"; /* Veya senin ana fontun */\n"
"    \n"
"    padding: 10px;              /* İçeriden boşluk ver ki sıkışmasın */\n"
"    text-align: left;           /* İkon solda, yazı sağda düzgün dursun */\n"
"    padding-left: 30px;         /* İkon ile sol kenar arası mesafe */\n"
"}\n"
"\n"
"/* --- Fare Üzerine Gelince (Hover) --- */\n"
"QPushButton#pushButton_KAYIT:hover {\n"
"    background-color: #30303A;  /* Zemin hafif aydınlansın */\n"
"    border-color: #FF0000;      /* Çerçeve kırmızılaşsın (Kayıt sinyali gibi) */\n"
"}\n"
"\n"
"/* --- Basılma Efekti (Pressed) --- */\n"
"QPushButton#pushButton_KAYIT:pressed {\n"
"    background-color: #101015;  /* Basınca zemin iyice koyulaşsın (İçe göçme hissi) */\n"
"    border-color: #990000;      /* Çerçeve koyu kırmızı olsun */\n"
"    padding-top: 12px;          /* Yazıyı 2px aşağı it (Mekanik buton hissi verir) */\n"
"    padding-left: 17px;\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/ikonlar/resimler/record-2 5.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_KAYIT.setIcon(icon7)
        self.pushButton_KAYIT.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_KAYIT.setObjectName("pushButton_KAYIT")
        self.stackedWidget.addWidget(self.page_anaMenu)
        self.page_kamera = QtWidgets.QWidget()
        self.page_kamera.setObjectName("page_kamera")
        self.frame_anaKamera = QtWidgets.QFrame(self.page_kamera)
        self.frame_anaKamera.setGeometry(QtCore.QRect(20, 20, 1300, 731))
        self.frame_anaKamera.setMinimumSize(QtCore.QSize(1300, 731))
        self.frame_anaKamera.setStyleSheet("QFrame#frame_anaKamera{\n"
"    background-color: #000000;\n"
"    border: 3px solid #FF0000; /* Kırmızı \"REC / CANLI\" çerçevesi */\n"
"    border-radius: 32px;\n"
"}")
        self.frame_anaKamera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_anaKamera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_anaKamera.setObjectName("frame_anaKamera")
        self.frame_yanKamera1 = QtWidgets.QFrame(self.page_kamera)
        self.frame_yanKamera1.setGeometry(QtCore.QRect(1340, 20, 420, 236))
        self.frame_yanKamera1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frame_yanKamera1.setStyleSheet("/* --- Normal Hali --- */\n"
"QFrame#frame_yanKamera1 {\n"
"    background-color: #000000;\n"
"    border: 2px solid #333344;  /* Sönük Gri Çerçeve */\n"
"    border-radius: 32px;\n"
"}\n"
"\n"
"/* --- Mouse Üzerine Gelince (HOVER) --- */\n"
"QFrame#frame_yanKamera1:hover {\n"
"    border: 2px solid #00FFFF;  /* PARLAK TURKUAZ Çerçeve */\n"
"    background-color: #050510;  /* Zemin çok hafif aydınlansın */\n"
"}")
        self.frame_yanKamera1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_yanKamera1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_yanKamera1.setObjectName("frame_yanKamera1")
        self.frame_yanKamera2 = QtWidgets.QFrame(self.page_kamera)
        self.frame_yanKamera2.setGeometry(QtCore.QRect(1340, 276, 420, 236))
        self.frame_yanKamera2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frame_yanKamera2.setStyleSheet("/* --- Normal Hali --- */\n"
"QFrame#frame_yanKamera2 {\n"
"    background-color: #000000;\n"
"    border: 2px solid #333344;  /* Sönük Gri Çerçeve */\n"
"    border-radius: 32px;\n"
"}\n"
"\n"
"/* --- Mouse Üzerine Gelince (HOVER) --- */\n"
"QFrame#frame_yanKamera2:hover {\n"
"    border: 2px solid #00FFFF;  /* PARLAK TURKUAZ Çerçeve */\n"
"    background-color: #050510;  /* Zemin çok hafif aydınlansın */\n"
"}")
        self.frame_yanKamera2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_yanKamera2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_yanKamera2.setObjectName("frame_yanKamera2")
        self.frame_yanKamera3 = QtWidgets.QFrame(self.page_kamera)
        self.frame_yanKamera3.setGeometry(QtCore.QRect(1340, 532, 420, 211))
        self.frame_yanKamera3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frame_yanKamera3.setStyleSheet("/* --- Normal Hali --- */\n"
"QFrame#frame_yanKamera3 {\n"
"    background-color: #000000;\n"
"    border: 2px solid #333344;  /* Sönük Gri Çerçeve */\n"
"    border-radius: 32px;\n"
"}\n"
"\n"
"/* --- Mouse Üzerine Gelince (HOVER) --- */\n"
"QFrame#frame_yanKamera3:hover {\n"
"    border: 2px solid #00FFFF;  /* PARLAK TURKUAZ Çerçeve */\n"
"    background-color: #050510;  /* Zemin çok hafif aydınlansın */\n"
"}")
        self.frame_yanKamera3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_yanKamera3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_yanKamera3.setObjectName("frame_yanKamera3")
        self.stackedWidget.addWidget(self.page_kamera)
        self.page_navigasyon = QtWidgets.QWidget()
        self.page_navigasyon.setObjectName("page_navigasyon")
        self.label_navigasyonYazi = QtWidgets.QLabel(self.page_navigasyon)
        self.label_navigasyonYazi.setGeometry(QtCore.QRect(-4, 33, 1791, 81))
        self.label_navigasyonYazi.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;            /* Beyaz Yazı */\n"
"    font-family: \"Roboto Mono\"; /* İstediğin Font */\n"
"    font-size: 48px;           /* İstediğin Dev Punto */\n"
"    font-weight: bold;         /* Kalın */\n"
"    letter-spacing: 15px;       /* Harf aralığı (48 puntoda çok açılmasın diye 5px idealdir) */\n"
"    background-color: transparent;\n"
"}")
        self.label_navigasyonYazi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_navigasyonYazi.setObjectName("label_navigasyonYazi")
        self.frame_navigasyonAlan = QtWidgets.QFrame(self.page_navigasyon)
        self.frame_navigasyonAlan.setGeometry(QtCore.QRect(30, 140, 1721, 600))
        self.frame_navigasyonAlan.setStyleSheet("QFrame#frame_navigasyonAlan {\n"
"    background-color: #050510; /* Koyu Harita Zemini */\n"
"    border: 2px solid #444;    /* Çerçeve */\n"
"    border-radius: 32px;\n"
"}")
        self.frame_navigasyonAlan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_navigasyonAlan.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_navigasyonAlan.setObjectName("frame_navigasyonAlan")
        self.stackedWidget.addWidget(self.page_navigasyon)
        self.page_hakknda = QtWidgets.QWidget()
        self.page_hakknda.setObjectName("page_hakknda")
        self.label_sistemBilgisiVeLisans = QtWidgets.QLabel(self.page_hakknda)
        self.label_sistemBilgisiVeLisans.setGeometry(QtCore.QRect(10, 14, 1771, 91))
        self.label_sistemBilgisiVeLisans.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;            /* Beyaz Yazı */\n"
"    font-family: \"Roboto Mono\"; /* İstediğin Font */\n"
"    font-size: 48px;           /* İstediğin Dev Punto */\n"
"    font-weight: bold;         /* Kalın */\n"
"    letter-spacing: 15px;       /* Harf aralığı (48 puntoda çok açılmasın diye 5px idealdir) */\n"
"    background-color: transparent;\n"
"}")
        self.label_sistemBilgisiVeLisans.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sistemBilgisiVeLisans.setObjectName("label_sistemBilgisiVeLisans")
        self.frame_BilgiKart = QtWidgets.QFrame(self.page_hakknda)
        self.frame_BilgiKart.setGeometry(QtCore.QRect(102, 134, 1600, 600))
        self.frame_BilgiKart.setStyleSheet("QFrame #frame_BilgiKart {\n"
"    background-color: rgba(0, 0, 0, 150);\n"
"    border: 2px solid #00FFFF; /* Turkuaz Çerçeve */\n"
"    border-radius: 16px;\n"
"}")
        self.frame_BilgiKart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_BilgiKart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_BilgiKart.setObjectName("frame_BilgiKart")
        self.textBrowser_Bilgi = QtWidgets.QTextBrowser(self.frame_BilgiKart)
        self.textBrowser_Bilgi.setGeometry(QtCore.QRect(25, 21, 1551, 561))
        self.textBrowser_Bilgi.setStyleSheet("background-color: transparent; \n"
"color: #e0e0e0; \n"
"font-size: 16px; \n"
"line-height: 1.5;")
        self.textBrowser_Bilgi.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_Bilgi.setObjectName("textBrowser_Bilgi")
        self.stackedWidget.addWidget(self.page_hakknda)
        self.page_ayarlar = QtWidgets.QWidget()
        self.page_ayarlar.setObjectName("page_ayarlar")
        self.label_ayarlarYazi = QtWidgets.QLabel(self.page_ayarlar)
        self.label_ayarlarYazi.setGeometry(QtCore.QRect(10, 20, 1771, 91))
        self.label_ayarlarYazi.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;            /* Beyaz Yazı */\n"
"    font-family: \"Roboto Mono\"; /* İstediğin Font */\n"
"    font-size: 48px;           /* İstediğin Dev Punto */\n"
"    font-weight: bold;         /* Kalın */\n"
"    letter-spacing: 15px;       /* Harf aralığı (48 puntoda çok açılmasın diye 5px idealdir) */\n"
"    background-color: transparent;\n"
"}")
        self.label_ayarlarYazi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ayarlarYazi.setObjectName("label_ayarlarYazi")
        self.frame_genelAyarlar = QtWidgets.QFrame(self.page_ayarlar)
        self.frame_genelAyarlar.setGeometry(QtCore.QRect(40, 150, 480, 50))
        self.frame_genelAyarlar.setStyleSheet("QFrame#frame_genelAyarlar{\n"
"    background-color: #0A0A12;   /* Neredeyse siyah, çok koyu lacivert/gri zemin */\n"
"    border: 2px solid #00AAFF;   /* İŞTE O PARLAK MAVİ ÇERÇEVE */\n"
"    border-radius: 16px;         /* Köşeler hafif yuvarlak */\n"
"}")
        self.frame_genelAyarlar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_genelAyarlar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_genelAyarlar.setObjectName("frame_genelAyarlar")
        self.label_genelAyarlarYazi = QtWidgets.QLabel(self.frame_genelAyarlar)
        self.label_genelAyarlarYazi.setGeometry(QtCore.QRect(35, 5, 431, 41))
        self.label_genelAyarlarYazi.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 15px;           /* Harflerin arasını açtık */\n"
"    border: none;                  /* Çerçeve yok */\n"
"    background-color: transparent; /* Arka plan şeffaf */\n"
"    padding-bottom: 5px;           /* Çizgiyle yazı arasına hafif boşluk */\n"
"}")
        self.label_genelAyarlarYazi.setObjectName("label_genelAyarlarYazi")
        self.frame_kontrolAyarlari = QtWidgets.QFrame(self.page_ayarlar)
        self.frame_kontrolAyarlari.setGeometry(QtCore.QRect(40, 485, 480, 50))
        self.frame_kontrolAyarlari.setStyleSheet("QFrame#frame_kontrolAyarlari{\n"
"    background-color: #0A0A12;   /* Neredeyse siyah, çok koyu lacivert/gri zemin */\n"
"    border: 2px solid #00AAFF;   /* İŞTE O PARLAK MAVİ ÇERÇEVE */\n"
"    border-radius: 16px;         /* Köşeler hafif yuvarlak */\n"
"}")
        self.frame_kontrolAyarlari.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_kontrolAyarlari.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_kontrolAyarlari.setObjectName("frame_kontrolAyarlari")
        self.label_kontrolAyarlariYazi = QtWidgets.QLabel(self.frame_kontrolAyarlari)
        self.label_kontrolAyarlariYazi.setGeometry(QtCore.QRect(60, 5, 351, 41))
        self.label_kontrolAyarlariYazi.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 5px;           /* Harflerin arasını açtık */\n"
"    border: none;                  /* Çerçeve yok */\n"
"    background-color: transparent; /* Arka plan şeffaf */\n"
"    padding-bottom: 5px;           /* Çizgiyle yazı arasına hafif boşluk */\n"
"}")
        self.label_kontrolAyarlariYazi.setObjectName("label_kontrolAyarlariYazi")
        self.frame_guvenlikKontrolleri = QtWidgets.QFrame(self.page_ayarlar)
        self.frame_guvenlikKontrolleri.setGeometry(QtCore.QRect(700, 150, 480, 50))
        self.frame_guvenlikKontrolleri.setStyleSheet("QFrame#frame_guvenlikKontrolleri{\n"
"    background-color: #0A0A12;   /* Neredeyse siyah, çok koyu lacivert/gri zemin */\n"
"    border: 2px solid #FF4444;   /* İŞTE O PARLAK MAVİ ÇERÇEVE */\n"
"    border-radius: 16px;         /* Köşeler hafif yuvarlak */\n"
"}")
        self.frame_guvenlikKontrolleri.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_guvenlikKontrolleri.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_guvenlikKontrolleri.setObjectName("frame_guvenlikKontrolleri")
        self.label_guvenlikKontrolleriYazi = QtWidgets.QLabel(self.frame_guvenlikKontrolleri)
        self.label_guvenlikKontrolleriYazi.setGeometry(QtCore.QRect(30, 5, 411, 41))
        self.label_guvenlikKontrolleriYazi.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 5px;           /* Harflerin arasını açtık */\n"
"    border: none;                  /* Çerçeve yok */\n"
"    background-color: transparent; /* Arka plan şeffaf */\n"
"    padding-bottom: 5px;           /* Çizgiyle yazı arasına hafif boşluk */\n"
"}")
        self.label_guvenlikKontrolleriYazi.setObjectName("label_guvenlikKontrolleriYazi")
        self.frame_goruntuAyarlari = QtWidgets.QFrame(self.page_ayarlar)
        self.frame_goruntuAyarlari.setGeometry(QtCore.QRect(1265, 150, 480, 50))
        self.frame_goruntuAyarlari.setStyleSheet("QFrame#frame_goruntuAyarlari{\n"
"    background-color: #0A0A12;   /* Neredeyse siyah, çok koyu lacivert/gri zemin */\n"
"    border: 2px solid #00AAFF;   /* İŞTE O PARLAK MAVİ ÇERÇEVE */\n"
"    border-radius: 16px;         /* Köşeler hafif yuvarlak */\n"
"}")
        self.frame_goruntuAyarlari.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_goruntuAyarlari.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_goruntuAyarlari.setObjectName("frame_goruntuAyarlari")
        self.label_goruntuAyarlari = QtWidgets.QLabel(self.frame_goruntuAyarlari)
        self.label_goruntuAyarlari.setGeometry(QtCore.QRect(75, 5, 351, 41))
        self.label_goruntuAyarlari.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 5px;           /* Harflerin arasını açtık */\n"
"    border: none;                  /* Çerçeve yok */\n"
"    background-color: transparent; /* Arka plan şeffaf */\n"
"    padding-bottom: 5px;           /* Çizgiyle yazı arasına hafif boşluk */\n"
"}")
        self.label_goruntuAyarlari.setObjectName("label_goruntuAyarlari")
        self.frame_veriYedekleme = QtWidgets.QFrame(self.page_ayarlar)
        self.frame_veriYedekleme.setGeometry(QtCore.QRect(1265, 460, 480, 50))
        self.frame_veriYedekleme.setStyleSheet("QFrame#frame_veriYedekleme{\n"
"    background-color: #0A0A12;   /* Neredeyse siyah, çok koyu lacivert/gri zemin */\n"
"    border: 2px solid #00AAFF;   /* İŞTE O PARLAK MAVİ ÇERÇEVE */\n"
"    border-radius: 16px;         /* Köşeler hafif yuvarlak */\n"
"}")
        self.frame_veriYedekleme.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_veriYedekleme.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_veriYedekleme.setObjectName("frame_veriYedekleme")
        self.label_veriYedeklemeYazi = QtWidgets.QLabel(self.frame_veriYedekleme)
        self.label_veriYedeklemeYazi.setGeometry(QtCore.QRect(100, 5, 321, 41))
        self.label_veriYedeklemeYazi.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 5px;           /* Harflerin arasını açtık */\n"
"    border: none;                  /* Çerçeve yok */\n"
"    background-color: transparent; /* Arka plan şeffaf */\n"
"    padding-bottom: 5px;           /* Çizgiyle yazı arasına hafif boşluk */\n"
"}")
        self.label_veriYedeklemeYazi.setObjectName("label_veriYedeklemeYazi")
        self.label_sistemDili = QtWidgets.QLabel(self.page_ayarlar)
        self.label_sistemDili.setGeometry(QtCore.QRect(25, 225, 261, 41))
        self.label_sistemDili.setStyleSheet("color: #CCCCCC;        /* Hafif gri/beyaz */\n"
"font-size: 24px;       /* İdeal okuma boyutu */\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color: transparent;")
        self.label_sistemDili.setObjectName("label_sistemDili")
        self.comboBox_dilSecimi = QtWidgets.QComboBox(self.page_ayarlar)
        self.comboBox_dilSecimi.setGeometry(QtCore.QRect(280, 220, 341, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(-1)
        self.comboBox_dilSecimi.setFont(font)
        self.comboBox_dilSecimi.setStyleSheet("/* --- 1. ANA COMBOBOX (KAPALI HALİ) --- */\n"
"QComboBox {\n"
"    background-color: #151520;\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #444455;\n"
"    border-radius: 12px;\n"
"    padding: 8px 15px;\n"
"    font-size: 22px;\n"
"    font-family: \"Roboto Mono\";\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #00AAFF;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 40px;\n"
"}\n"
"\n"
"/* --- 2. AÇILAN LİSTENİN DIŞ KUTUSU --- */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #151520;\n"
"    border: 2px solid #00AAFF;\n"
"    border-radius: 12px;\n"
"    padding: 6px;         /* İŞTE ÇÖZÜM: Listenin iç duvarlarına 6px yastık koyduk */\n"
"    outline: none;\n"
"}\n"
"\n"
"/* --- 3. LİSTE ELEMANLARI (Türkçe, English) --- */\n"
"QComboBox QAbstractItemView::item {\n"
"    color: #FFFFFF;\n"
"    min-height: 40px;\n"
"    border-radius: 6px;   /* Şıkların da köşelerini yuvarladık */\n"
"}\n"
"\n"
"/* --- 4. SEÇİLİ OLAN ŞIK (Mavi Yanan Kısım) --- */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #00AAFF;\n"
"    color: #FFFFFF;\n"
"    border-radius: 6px;   /* MAVİ SEÇİMİN KÖŞELERİ KESİNLİKLE YUVARLAK OLACAK */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #00AAFF;\n"
"    color: #FFFFFF;\n"
"    border-radius: 6px;\n"
"}")
        self.comboBox_dilSecimi.setObjectName("comboBox_dilSecimi")
        self.comboBox_dilSecimi.addItem("")
        self.comboBox_dilSecimi.addItem("")
        self.comboBox_temaSecimi = QtWidgets.QComboBox(self.page_ayarlar)
        self.comboBox_temaSecimi.setGeometry(QtCore.QRect(280, 315, 341, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(-1)
        self.comboBox_temaSecimi.setFont(font)
        self.comboBox_temaSecimi.setStyleSheet("/* --- 1. ANA COMBOBOX (KAPALI HALİ) --- */\n"
"QComboBox {\n"
"    background-color: #151520;\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #444455;\n"
"    border-radius: 12px;\n"
"    padding: 8px 15px;\n"
"    font-size: 22px;\n"
"    font-family: \"Roboto Mono\";\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #00AAFF;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 40px;\n"
"}\n"
"\n"
"/* --- 2. AÇILAN LİSTENİN DIŞ KUTUSU --- */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #151520;\n"
"    border: 2px solid #00AAFF;\n"
"    border-radius: 12px;\n"
"    padding: 6px;         /* İŞTE ÇÖZÜM: Listenin iç duvarlarına 6px yastık koyduk */\n"
"    outline: none;\n"
"}\n"
"\n"
"/* --- 3. LİSTE ELEMANLARI (Türkçe, English) --- */\n"
"QComboBox QAbstractItemView::item {\n"
"    color: #FFFFFF;\n"
"    min-height: 40px;\n"
"    border-radius: 6px;   /* Şıkların da köşelerini yuvarladık */\n"
"}\n"
"\n"
"/* --- 4. SEÇİLİ OLAN ŞIK (Mavi Yanan Kısım) --- */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #00AAFF;\n"
"    color: #FFFFFF;\n"
"    border-radius: 6px;   /* MAVİ SEÇİMİN KÖŞELERİ KESİNLİKLE YUVARLAK OLACAK */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #00AAFF;\n"
"    color: #FFFFFF;\n"
"    border-radius: 6px;\n"
"}")
        self.comboBox_temaSecimi.setObjectName("comboBox_temaSecimi")
        self.comboBox_temaSecimi.addItem("")
        self.comboBox_temaSecimi.addItem("")
        self.label_tema = QtWidgets.QLabel(self.page_ayarlar)
        self.label_tema.setGeometry(QtCore.QRect(25, 315, 261, 41))
        self.label_tema.setStyleSheet("color: #CCCCCC;        /* Hafif gri/beyaz */\n"
"font-size: 24px;       /* İdeal okuma boyutu */\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color: transparent;")
        self.label_tema.setObjectName("label_tema")
        self.label_bildirimler = QtWidgets.QLabel(self.page_ayarlar)
        self.label_bildirimler.setGeometry(QtCore.QRect(25, 405, 261, 41))
        self.label_bildirimler.setStyleSheet("color: #CCCCCC;        /* Hafif gri/beyaz */\n"
"font-size: 24px;       /* İdeal okuma boyutu */\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color: transparent;")
        self.label_bildirimler.setObjectName("label_bildirimler")
        self.pushButton_bildirimler = QtWidgets.QPushButton(self.page_ayarlar)
        self.pushButton_bildirimler.setGeometry(QtCore.QRect(280, 405, 130, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_bildirimler.sizePolicy().hasHeightForWidth())
        self.pushButton_bildirimler.setSizePolicy(sizePolicy)
        self.pushButton_bildirimler.setMinimumSize(QtCore.QSize(130, 0))
        self.pushButton_bildirimler.setMaximumSize(QtCore.QSize(130, 40))
        self.pushButton_bildirimler.setStyleSheet("QPushButton {\n"
"    background-color: #22222A;\n"
"    color: #888888;\n"
"    border: 2px solid #444455;\n"
"    \n"
"    /* İŞTE KUSURSUZ HAP (PILL) MATEMATİĞİ (40\'ın yarısı) */\n"
"    border-radius: 20px; \n"
"    \n"
"    /* DİKKAT: Üst ve alt boşluğu SIFIR (0px) yaptık ki şişmesin! Sadece yanlardan boşluk verdik. */\n"
"    padding: 0px 20px; \n"
"    \n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: \"Roboto Mono\";\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #00AAFF;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #00AAFF;\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #00FFFF;\n"
"}\n"
"\n"
"QPushButton:checked:hover {\n"
"    background-color: #00BBFF;\n"
"}")
        self.pushButton_bildirimler.setCheckable(True)
        self.pushButton_bildirimler.setChecked(True)
        self.pushButton_bildirimler.setObjectName("pushButton_bildirimler")
        self.label_VPN = QtWidgets.QLabel(self.page_ayarlar)
        self.label_VPN.setGeometry(QtCore.QRect(700, 220, 101, 41))
        self.label_VPN.setStyleSheet("color: #CCCCCC;        /* Hafif gri/beyaz */\n"
"font-size: 24px;       /* İdeal okuma boyutu */\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color: transparent;")
        self.label_VPN.setObjectName("label_VPN")
        self.comboBox_VPNsecimi = QtWidgets.QComboBox(self.page_ayarlar)
        self.comboBox_VPNsecimi.setGeometry(QtCore.QRect(820, 220, 341, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(-1)
        self.comboBox_VPNsecimi.setFont(font)
        self.comboBox_VPNsecimi.setStyleSheet("/* --- 1. ANA COMBOBOX (KAPALI HALİ) --- */\n"
"QComboBox {\n"
"    background-color: #151520;\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #444455;\n"
"    border-radius: 12px;\n"
"    padding: 8px 15px;\n"
"    font-size: 22px;\n"
"    font-family: \"Roboto Mono\";\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #00AAFF;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 40px;\n"
"}\n"
"\n"
"/* --- 2. AÇILAN LİSTENİN DIŞ KUTUSU --- */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #151520;\n"
"    border: 2px solid #00AAFF;\n"
"    border-radius: 12px;\n"
"    padding: 6px;         /* İŞTE ÇÖZÜM: Listenin iç duvarlarına 6px yastık koyduk */\n"
"    outline: none;\n"
"}\n"
"\n"
"/* --- 3. LİSTE ELEMANLARI (Türkçe, English) --- */\n"
"QComboBox QAbstractItemView::item {\n"
"    color: #FFFFFF;\n"
"    min-height: 40px;\n"
"    border-radius: 6px;   /* Şıkların da köşelerini yuvarladık */\n"
"}\n"
"\n"
"/* --- 4. SEÇİLİ OLAN ŞIK (Mavi Yanan Kısım) --- */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #00AAFF;\n"
"    color: #FFFFFF;\n"
"    border-radius: 6px;   /* MAVİ SEÇİMİN KÖŞELERİ KESİNLİKLE YUVARLAK OLACAK */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #00AAFF;\n"
"    color: #FFFFFF;\n"
"    border-radius: 6px;\n"
"}")
        self.comboBox_VPNsecimi.setObjectName("comboBox_VPNsecimi")
        self.comboBox_VPNsecimi.addItem("")
        self.comboBox_VPNsecimi.addItem("")
        self.lineEdit_kullaniciAdi = QtWidgets.QLineEdit(self.page_ayarlar)
        self.lineEdit_kullaniciAdi.setGeometry(QtCore.QRect(700, 337, 400, 45))
        self.lineEdit_kullaniciAdi.setStyleSheet("QLineEdit {\n"
"    background-color: #151520;  /* Koyu arka plan */\n"
"    color: #FFFFFF;             /* Yazı rengi beyaz */\n"
"    border: 1px solid #444455;  /* Sönük gri çerçeve */\n"
"    border-radius: 12px;         /* Köşeler hafif yuvarlak */\n"
"    padding: 5px 10px;          /* İçeriden boşluk (ferah dursun) */\n"
"    font-size: 26px;\n"
"    font-family: \"Roboto Mono\";\n"
"}\n"
"\n"
"/* Mouse ile içine tıklanıp YAZI YAZILMAYA BAŞLANDIĞINDA (Focus) */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #00AAFF;  /* Çerçeve Mavi Parlasın */\n"
"    background-color: #1A1A25;\n"
"}")
        self.lineEdit_kullaniciAdi.setObjectName("lineEdit_kullaniciAdi")
        self.label_kullaniciAdi = QtWidgets.QLabel(self.page_ayarlar)
        self.label_kullaniciAdi.setGeometry(QtCore.QRect(700, 285, 271, 41))
        self.label_kullaniciAdi.setStyleSheet("color: #CCCCCC;        /* Hafif gri/beyaz */\n"
"font-size: 24px;       /* İdeal okuma boyutu */\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color: transparent;")
        self.label_kullaniciAdi.setObjectName("label_kullaniciAdi")
        self.label_sifre = QtWidgets.QLabel(self.page_ayarlar)
        self.label_sifre.setGeometry(QtCore.QRect(700, 400, 121, 41))
        self.label_sifre.setStyleSheet("color: #CCCCCC;        /* Hafif gri/beyaz */\n"
"font-size:24px;       /* İdeal okuma boyutu */\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color: transparent;")
        self.label_sifre.setObjectName("label_sifre")
        self.lineEdit_sifre = QtWidgets.QLineEdit(self.page_ayarlar)
        self.lineEdit_sifre.setGeometry(QtCore.QRect(830, 400, 350, 45))
        self.lineEdit_sifre.setStyleSheet("QLineEdit {\n"
"    background-color: #151520;  /* Koyu arka plan */\n"
"    color: #FFFFFF;             /* Yazı rengi beyaz */\n"
"    border: 1px solid #444455;  /* Sönük gri çerçeve */\n"
"    border-radius: 12px;         /* Köşeler hafif yuvarlak */\n"
"    padding: 5px 10px;          /* İçeriden boşluk (ferah dursun) */\n"
"    font-size: 26px;\n"
"    font-family: \"Roboto Mono\";\n"
"}\n"
"\n"
"/* Mouse ile içine tıklanıp YAZI YAZILMAYA BAŞLANDIĞINDA (Focus) */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #00AAFF;  /* Çerçeve Mavi Parlasın */\n"
"    background-color: #1A1A25;\n"
"}")
        self.lineEdit_sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_sifre.setObjectName("lineEdit_sifre")
        self.label_telefon = QtWidgets.QLabel(self.page_ayarlar)
        self.label_telefon.setGeometry(QtCore.QRect(700, 466, 171, 41))
        self.label_telefon.setStyleSheet("color: #CCCCCC;        /* Hafif gri/beyaz */\n"
"font-size: 24px;       /* İdeal okuma boyutu */\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color: transparent;")
        self.label_telefon.setObjectName("label_telefon")
        self.lineEdit_kullaniciAdi_2 = QtWidgets.QLineEdit(self.page_ayarlar)
        self.lineEdit_kullaniciAdi_2.setGeometry(QtCore.QRect(880, 466, 300, 45))
        self.lineEdit_kullaniciAdi_2.setStyleSheet("QLineEdit {\n"
"    background-color: #151520;  /* Koyu arka plan */\n"
"    color: #FFFFFF;             /* Yazı rengi beyaz */\n"
"    border: 1px solid #444455;  /* Sönük gri çerçeve */\n"
"    border-radius: 12px;         /* Köşeler hafif yuvarlak */\n"
"    padding: 5px 10px;          /* İçeriden boşluk (ferah dursun) */\n"
"    font-size: 26px;\n"
"    font-family: \"Roboto Mono\";\n"
"}\n"
"\n"
"/* Mouse ile içine tıklanıp YAZI YAZILMAYA BAŞLANDIĞINDA (Focus) */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #00AAFF;  /* Çerçeve Mavi Parlasın */\n"
"    background-color: #1A1A25;\n"
"}")
        self.lineEdit_kullaniciAdi_2.setText("")
        self.lineEdit_kullaniciAdi_2.setObjectName("lineEdit_kullaniciAdi_2")
        self.label_canliSistemLog = QtWidgets.QLabel(self.page_ayarlar)
        self.label_canliSistemLog.setGeometry(QtCore.QRect(700, 530, 341, 41))
        self.label_canliSistemLog.setStyleSheet("color: #CCCCCC;        /* Hafif gri/beyaz */\n"
"font-size: 24px;       /* İdeal okuma boyutu */\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color: transparent;")
        self.label_canliSistemLog.setObjectName("label_canliSistemLog")
        self.textEdit_canliSistemLog = QtWidgets.QTextEdit(self.page_ayarlar)
        self.textEdit_canliSistemLog.setGeometry(QtCore.QRect(660, 590, 390, 171))
        self.textEdit_canliSistemLog.setStyleSheet("QTextEdit {\n"
"    background-color: #05050A;     /* Simsiyah, derin terminal arka planı */\n"
"    color: #00FF00;                /* Neon / Hacker Yeşili yazı rengi */\n"
"    border: 2px solid #333344;     /* Koyu gri ince çerçeve */\n"
"    border-radius: 48px;           /* Fotoğraftaki gibi yuvarlak hatlar */\n"
"    padding: 10px;                 /* Yazılar kenara yapışmasın diye iç boşluk */\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Roboto Mono\", \"Consolas\"; /* Tam bir yazılımcı fontu */\n"
"}\n"
"\n"
"/* Sağdaki kaydırma çubuğunu (Scrollbar) da arayüze uyduralım (Opsiyonel ama çok şık olur) */\n"
"QTextEdit QScrollBar:vertical {\n"
"    background: #111;\n"
"    width: 10px;\n"
"}\n"
"QTextEdit QScrollBar::handle:vertical {\n"
"    background: #444;\n"
"    border-radius: 5px;\n"
"}")
        self.textEdit_canliSistemLog.setReadOnly(True)
        self.textEdit_canliSistemLog.setObjectName("textEdit_canliSistemLog")
        self.label_joystick = QtWidgets.QLabel(self.page_ayarlar)
        self.label_joystick.setGeometry(QtCore.QRect(25, 550, 191, 41))
        self.label_joystick.setStyleSheet("color: #CCCCCC;        /* Hafif gri/beyaz */\n"
"font-size: 24px;       /* İdeal okuma boyutu */\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color: transparent;")
        self.label_joystick.setObjectName("label_joystick")
        self.pushButton_joystick = QtWidgets.QPushButton(self.page_ayarlar)
        self.pushButton_joystick.setGeometry(QtCore.QRect(280, 550, 130, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_joystick.sizePolicy().hasHeightForWidth())
        self.pushButton_joystick.setSizePolicy(sizePolicy)
        self.pushButton_joystick.setMinimumSize(QtCore.QSize(130, 0))
        self.pushButton_joystick.setMaximumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_joystick.setFont(font)
        self.pushButton_joystick.setStyleSheet("QPushButton {\n"
"    background-color: #22222A;\n"
"    color: #888888;\n"
"    border: 2px solid #444455;\n"
"    \n"
"    /* İŞTE KUSURSUZ HAP (PILL) MATEMATİĞİ (40\'ın yarısı) */\n"
"    border-radius: 20px; \n"
"    \n"
"    /* DİKKAT: Üst ve alt boşluğu SIFIR (0px) yaptık ki şişmesin! Sadece yanlardan boşluk verdik. */\n"
"    padding: 0px 20px; \n"
"    \n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: \"Roboto Mono\";\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #00AAFF;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #00AAFF;\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #00FFFF;\n"
"}\n"
"\n"
"QPushButton:checked:hover {\n"
"    background-color: #00BBFF;\n"
"}")
        self.pushButton_joystick.setCheckable(True)
        self.pushButton_joystick.setChecked(True)
        self.pushButton_joystick.setObjectName("pushButton_joystick")
        self.label_klavyeKontrol = QtWidgets.QLabel(self.page_ayarlar)
        self.label_klavyeKontrol.setGeometry(QtCore.QRect(25, 640, 311, 41))
        self.label_klavyeKontrol.setStyleSheet("color: #CCCCCC;        /* Hafif gri/beyaz */\n"
"font-size: 24px;       /* İdeal okuma boyutu */\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color: transparent;")
        self.label_klavyeKontrol.setObjectName("label_klavyeKontrol")
        self.pushButton_klavye = QtWidgets.QPushButton(self.page_ayarlar)
        self.pushButton_klavye.setGeometry(QtCore.QRect(360, 640, 130, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_klavye.sizePolicy().hasHeightForWidth())
        self.pushButton_klavye.setSizePolicy(sizePolicy)
        self.pushButton_klavye.setMinimumSize(QtCore.QSize(130, 0))
        self.pushButton_klavye.setMaximumSize(QtCore.QSize(130, 40))
        self.pushButton_klavye.setStyleSheet("QPushButton {\n"
"    background-color: #22222A;\n"
"    color: #888888;\n"
"    border: 2px solid #444455;\n"
"    \n"
"    /* İŞTE KUSURSUZ HAP (PILL) MATEMATİĞİ (40\'ın yarısı) */\n"
"    border-radius: 20px; \n"
"    \n"
"    /* DİKKAT: Üst ve alt boşluğu SIFIR (0px) yaptık ki şişmesin! Sadece yanlardan boşluk verdik. */\n"
"    padding: 0px 20px; \n"
"    \n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: \"Roboto Mono\";\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #00AAFF;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #00AAFF;\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #00FFFF;\n"
"}\n"
"\n"
"QPushButton:checked:hover {\n"
"    background-color: #00BBFF;\n"
"}")
        self.pushButton_klavye.setCheckable(True)
        self.pushButton_klavye.setChecked(True)
        self.pushButton_klavye.setObjectName("pushButton_klavye")
        self.comboBox_yayinKalite = QtWidgets.QComboBox(self.page_ayarlar)
        self.comboBox_yayinKalite.setGeometry(QtCore.QRect(1270, 277, 350, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(-1)
        self.comboBox_yayinKalite.setFont(font)
        self.comboBox_yayinKalite.setStyleSheet("/* --- 1. ANA COMBOBOX (KAPALI HALİ) --- */\n"
"QComboBox {\n"
"    background-color: #151520;\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #444455;\n"
"    border-radius: 12px;\n"
"    padding: 8px 15px;\n"
"    font-size: 22px;\n"
"    font-family: \"Roboto Mono\";\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #00AAFF;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 40px;\n"
"}\n"
"\n"
"/* --- 2. AÇILAN LİSTENİN DIŞ KUTUSU --- */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #151520;\n"
"    border: 2px solid #00AAFF;\n"
"    border-radius: 12px;\n"
"    padding: 6px;         /* İŞTE ÇÖZÜM: Listenin iç duvarlarına 6px yastık koyduk */\n"
"    outline: none;\n"
"}\n"
"\n"
"/* --- 3. LİSTE ELEMANLARI (Türkçe, English) --- */\n"
"QComboBox QAbstractItemView::item {\n"
"    color: #FFFFFF;\n"
"    min-height: 40px;\n"
"    border-radius: 6px;   /* Şıkların da köşelerini yuvarladık */\n"
"}\n"
"\n"
"/* --- 4. SEÇİLİ OLAN ŞIK (Mavi Yanan Kısım) --- */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #00AAFF;\n"
"    color: #FFFFFF;\n"
"    border-radius: 6px;   /* MAVİ SEÇİMİN KÖŞELERİ KESİNLİKLE YUVARLAK OLACAK */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #00AAFF;\n"
"    color: #FFFFFF;\n"
"    border-radius: 6px;\n"
"}")
        self.comboBox_yayinKalite.setObjectName("comboBox_yayinKalite")
        self.comboBox_yayinKalite.addItem("")
        self.comboBox_yayinKalite.addItem("")
        self.comboBox_yayinKalite.addItem("")
        self.label_yayinKalite = QtWidgets.QLabel(self.page_ayarlar)
        self.label_yayinKalite.setGeometry(QtCore.QRect(1270, 225, 301, 41))
        self.label_yayinKalite.setStyleSheet("color: #CCCCCC;        /* Hafif gri/beyaz */\n"
"font-size: 24px;       /* İdeal okuma boyutu */\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color: transparent;")
        self.label_yayinKalite.setObjectName("label_yayinKalite")
        self.label_FPS = QtWidgets.QLabel(self.page_ayarlar)
        self.label_FPS.setGeometry(QtCore.QRect(1270, 337, 301, 41))
        self.label_FPS.setStyleSheet("color: #CCCCCC;        /* Hafif gri/beyaz */\n"
"font-size: 24px;       /* İdeal okuma boyutu */\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color: transparent;")
        self.label_FPS.setObjectName("label_FPS")
        self.comboBox_FPS = QtWidgets.QComboBox(self.page_ayarlar)
        self.comboBox_FPS.setGeometry(QtCore.QRect(1270, 382, 350, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(-1)
        self.comboBox_FPS.setFont(font)
        self.comboBox_FPS.setStyleSheet("/* --- 1. ANA COMBOBOX (KAPALI HALİ) --- */\n"
"QComboBox {\n"
"    background-color: #151520;\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #444455;\n"
"    border-radius: 12px;\n"
"    padding: 8px 15px;\n"
"    font-size: 22px;\n"
"    font-family: \"Roboto Mono\";\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #00AAFF;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 40px;\n"
"}\n"
"\n"
"/* --- 2. AÇILAN LİSTENİN DIŞ KUTUSU --- */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #151520;\n"
"    border: 2px solid #00AAFF;\n"
"    border-radius: 12px;\n"
"    padding: 6px;         /* İŞTE ÇÖZÜM: Listenin iç duvarlarına 6px yastık koyduk */\n"
"    outline: none;\n"
"}\n"
"\n"
"/* --- 3. LİSTE ELEMANLARI (Türkçe, English) --- */\n"
"QComboBox QAbstractItemView::item {\n"
"    color: #FFFFFF;\n"
"    min-height: 40px;\n"
"    border-radius: 6px;   /* Şıkların da köşelerini yuvarladık */\n"
"}\n"
"\n"
"/* --- 4. SEÇİLİ OLAN ŞIK (Mavi Yanan Kısım) --- */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #00AAFF;\n"
"    color: #FFFFFF;\n"
"    border-radius: 6px;   /* MAVİ SEÇİMİN KÖŞELERİ KESİNLİKLE YUVARLAK OLACAK */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #00AAFF;\n"
"    color: #FFFFFF;\n"
"    border-radius: 6px;\n"
"}")
        self.comboBox_FPS.setObjectName("comboBox_FPS")
        self.comboBox_FPS.addItem("")
        self.comboBox_FPS.addItem("")
        self.lineEdit_hedefKlasor = QtWidgets.QLineEdit(self.page_ayarlar)
        self.lineEdit_hedefKlasor.setGeometry(QtCore.QRect(1270, 573, 350, 45))
        self.lineEdit_hedefKlasor.setStyleSheet("QLineEdit {\n"
"    background-color: #151520;  /* Koyu arka plan */\n"
"    color: #FFFFFF;             /* Yazı rengi beyaz */\n"
"    border: 1px solid #444455;  /* Sönük gri çerçeve */\n"
"    border-radius: 12px;         /* Köşeler hafif yuvarlak */\n"
"    padding: 5px 10px;          /* İçeriden boşluk (ferah dursun) */\n"
"    font-size: 26px;\n"
"    font-family: \"Roboto Mono\";\n"
"}\n"
"\n"
"/* Mouse ile içine tıklanıp YAZI YAZILMAYA BAŞLANDIĞINDA (Focus) */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #00AAFF;  /* Çerçeve Mavi Parlasın */\n"
"    background-color: #1A1A25;\n"
"}")
        self.lineEdit_hedefKlasor.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_hedefKlasor.setObjectName("lineEdit_hedefKlasor")
        self.label_hedefKlasor = QtWidgets.QLabel(self.page_ayarlar)
        self.label_hedefKlasor.setGeometry(QtCore.QRect(1270, 529, 281, 41))
        self.label_hedefKlasor.setStyleSheet("color: #CCCCCC;        /* Hafif gri/beyaz */\n"
"font-size: 24px;       /* İdeal okuma boyutu */\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color: transparent;")
        self.label_hedefKlasor.setObjectName("label_hedefKlasor")
        self.label_sifreleme = QtWidgets.QLabel(self.page_ayarlar)
        self.label_sifreleme.setGeometry(QtCore.QRect(1270, 635, 211, 41))
        self.label_sifreleme.setStyleSheet("color: #CCCCCC;        /* Hafif gri/beyaz */\n"
"font-size: 24px;       /* İdeal okuma boyutu */\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color: transparent;")
        self.label_sifreleme.setObjectName("label_sifreleme")
        self.pushButton_sifreleme = QtWidgets.QPushButton(self.page_ayarlar)
        self.pushButton_sifreleme.setGeometry(QtCore.QRect(1520, 635, 130, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_sifreleme.sizePolicy().hasHeightForWidth())
        self.pushButton_sifreleme.setSizePolicy(sizePolicy)
        self.pushButton_sifreleme.setMinimumSize(QtCore.QSize(130, 0))
        self.pushButton_sifreleme.setMaximumSize(QtCore.QSize(130, 40))
        self.pushButton_sifreleme.setStyleSheet("QPushButton {\n"
"    background-color: #22222A;\n"
"    color: #888888;\n"
"    border: 2px solid #444455;\n"
"    \n"
"    /* İŞTE KUSURSUZ HAP (PILL) MATEMATİĞİ (40\'ın yarısı) */\n"
"    border-radius: 20px; \n"
"    \n"
"    /* DİKKAT: Üst ve alt boşluğu SIFIR (0px) yaptık ki şişmesin! Sadece yanlardan boşluk verdik. */\n"
"    padding: 0px 20px; \n"
"    \n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: \"Roboto Mono\";\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #00AAFF;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #00AAFF;\n"
"    color: #FFFFFF;\n"
"    border: 2px solid #00FFFF;\n"
"}\n"
"\n"
"QPushButton:checked:hover {\n"
"    background-color: #00BBFF;\n"
"}")
        self.pushButton_sifreleme.setCheckable(True)
        self.pushButton_sifreleme.setChecked(True)
        self.pushButton_sifreleme.setObjectName("pushButton_sifreleme")
        self.pushButton_simdiYedekle = QtWidgets.QPushButton(self.page_ayarlar)
        self.pushButton_simdiYedekle.setGeometry(QtCore.QRect(1270, 699, 450, 50))
        self.pushButton_simdiYedekle.setStyleSheet("QPushButton {\n"
"    background-color: #1F1F2E; /* İçi boş (arkaplan rengi yok) */\n"
"    color: #00AAFF;                /* Mavi yazı */\n"
"    border: 2px solid #003366;     /* Koyu mavi çerçeve */\n"
"    border-radius: 16px;            /* Hafif yuvarlak köşeler */\n"
"    padding: 8px;\n"
"    font-size: 26px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 2px;           /* Harf arası boşluk (Destekliyorsa şık durur) */\n"
"}\n"
"\n"
"/* Mouse üzerine gelince */\n"
"QPushButton:hover {\n"
"    border: 2px solid #00AAFF;     /* Çerçeve parlak mavi olur */\n"
"    background-color: #001122;     /* İçi çok hafif mavi/siyah dolar */\n"
"}\n"
"\n"
"/* Tıklanırken */\n"
"QPushButton:pressed {\n"
"    background-color: #00AAFF;     /* İçi tamamen mavi olur */\n"
"    color: #FFFFFF;                /* Yazı beyaz olur */\n"
"}")
        self.pushButton_simdiYedekle.setObjectName("pushButton_simdiYedekle")
        self.stackedWidget.addWidget(self.page_ayarlar)
        self.gridLayout_6.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.alt_bar = QtWidgets.QFrame(self.icerik_frame)
        self.alt_bar.setMinimumSize(QtCore.QSize(1750, 280))
        self.alt_bar.setMaximumSize(QtCore.QSize(1750, 280))
        self.alt_bar.setStyleSheet("background-color: #1A1A24; /* Sol menüyle aynı renk olsun bütünlük sağlasın */\n"
"border-radius: 16px;")
        self.alt_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.alt_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.alt_bar.setObjectName("alt_bar")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.alt_bar)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(18)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.log_ekran = QtWidgets.QFrame(self.alt_bar)
        self.log_ekran.setMinimumSize(QtCore.QSize(950, 250))
        self.log_ekran.setMaximumSize(QtCore.QSize(950, 250))
        self.log_ekran.setStyleSheet("QFrame#log_ekran {\n"
"    background-color: #000000;      /* Tam Siyah Arka Plan */\n"
"    border: 2px solid #00FF41;      /* Matrix Yeşili Çerçeve */\n"
"    border-radius: 16px;            /* Köşeleri Yuvarla */\n"
"}")
        self.log_ekran.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.log_ekran.setFrameShadow(QtWidgets.QFrame.Raised)
        self.log_ekran.setObjectName("log_ekran")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.log_ekran)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.terminal_ekrani = QtWidgets.QTextEdit(self.log_ekran)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(5)
        self.terminal_ekrani.setFont(font)
        self.terminal_ekrani.setStyleSheet("QTextEdit {\n"
"    background-color: transparent;      /* Arka planı simsiyah yapar */\n"
"    color: #00FF00;               /* Yazıları fosforlu terminal yeşili yapar */\n"
"    \n"
"    font-family: \"Roboto Mono\";   /* Gerçek terminal yazısı gibi daktilo fontu yapar */\n"
"      \n"
"    border-radius: 5px;           /* Köşeleri hafif yuvarlatır */\n"
"}")
        self.terminal_ekrani.setObjectName("terminal_ekrani")
        self.gridLayout_4.addWidget(self.terminal_ekrani, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.log_ekran)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(20)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_hiz = QtWidgets.QFrame(self.alt_bar)
        self.frame_hiz.setMinimumSize(QtCore.QSize(280, 150))
        self.frame_hiz.setMaximumSize(QtCore.QSize(280, 150))
        self.frame_hiz.setStyleSheet("QFrame#frame_hiz {\n"
"    background-color: #14141E;   /* Koyu Arka Plan */\n"
"    border-radius: 16px;         /* Yuvarlak Köşeler */\n"
"}")
        self.frame_hiz.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_hiz.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_hiz.setObjectName("frame_hiz")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_hiz)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_hiz = QtWidgets.QLabel(self.frame_hiz)
        self.label_hiz.setStyleSheet("QLabel#label_hiz {\n"
"    background-color: transparent   /* Koyu Arka Plan */\n"
"          \n"
"}")
        self.label_hiz.setText("")
        self.label_hiz.setPixmap(QtGui.QPixmap(":/ikonlar/resimler/speed 1.svg"))
        self.label_hiz.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hiz.setObjectName("label_hiz")
        self.verticalLayout.addWidget(self.label_hiz)
        self.label_hizYazi = QtWidgets.QLabel(self.frame_hiz)
        self.label_hizYazi.setStyleSheet("color: #FFFFFF;         /* Beyaz Yazı */\n"
"font-size: 30px;        /* Büyük Punto */\n"
"font-weight: bold;      /* Kalın */\n"
"background-color: transparent;")
        self.label_hizYazi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hizYazi.setObjectName("label_hizYazi")
        self.verticalLayout.addWidget(self.label_hizYazi)
        self.verticalLayout_11.addWidget(self.frame_hiz)
        self.pushButton_manuel = QtWidgets.QPushButton(self.alt_bar)
        self.pushButton_manuel.setMinimumSize(QtCore.QSize(280, 80))
        self.pushButton_manuel.setMaximumSize(QtCore.QSize(280, 80))
        self.pushButton_manuel.setStyleSheet("QPushButton {\n"
"    background-color: #0066FF;  /* Canlı Mavi */\n"
"    color: #FFFFFF;             /* Bembeyaz Yazı */\n"
"    border-radius: 16px;         /* Köşeleri hafif yumuşat */\n"
"    font-weight: bold;          /* Yazı kalın olsun */\n"
"    font-size: 28px;            /* Okunabilir büyüklükte */\n"
"    border: none;               /* Kenarlık yok */\n"
"}\n"
"\n"
"/* Tıklama Efekti (Opsiyonel ama hoş durur) */\n"
"QPushButton:pressed {\n"
"    background-color: #0044AA;  /* Tıklayınca koyulaşsın */\n"
"}")
        self.pushButton_manuel.setObjectName("pushButton_manuel")
        self.verticalLayout_11.addWidget(self.pushButton_manuel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(20)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_etap = QtWidgets.QFrame(self.alt_bar)
        self.frame_etap.setMinimumSize(QtCore.QSize(280, 150))
        self.frame_etap.setMaximumSize(QtCore.QSize(280, 150))
        self.frame_etap.setStyleSheet("QFrame#frame_etap {\n"
"    background-color: #14141E;   /* Koyu Arka Plan */\n"
"    border-radius: 16px;         /* Yuvarlak Köşeler */\n"
"}")
        self.frame_etap.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_etap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_etap.setObjectName("frame_etap")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_etap)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_etap = QtWidgets.QLabel(self.frame_etap)
        self.label_etap.setStyleSheet("color: #FFFFFF;         /* Beyaz Yazı */\n"
"font-size: 30px;        /* Büyük Punto */\n"
"font-weight: bold;      /* Kalın */\n"
"background-color: transparent;")
        self.label_etap.setAlignment(QtCore.Qt.AlignCenter)
        self.label_etap.setObjectName("label_etap")
        self.verticalLayout_2.addWidget(self.label_etap)
        self.label_etapNo = QtWidgets.QLabel(self.frame_etap)
        self.label_etapNo.setStyleSheet("color: #FFFFFF;         /* Beyaz Yazı */\n"
"font-size: 48px;        /* Büyük Punto */\n"
"font-weight: bold;      /* Kalın */\n"
"background-color: transparent;")
        self.label_etapNo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_etapNo.setObjectName("label_etapNo")
        self.verticalLayout_2.addWidget(self.label_etapNo)
        self.verticalLayout_10.addWidget(self.frame_etap)
        self.pushButton_Otonom = QtWidgets.QPushButton(self.alt_bar)
        self.pushButton_Otonom.setMinimumSize(QtCore.QSize(280, 80))
        self.pushButton_Otonom.setMaximumSize(QtCore.QSize(280, 80))
        self.pushButton_Otonom.setStyleSheet("QPushButton {\n"
"    background-color: #22222E;  /* Arka planla neredeyse aynı koyu gri */\n"
"    color: #555566;             /* Yazı da gri ve sönük */\n"
"    border-radius: 16px;\n"
"    font-weight: bold;\n"
"    font-size: 28px;\n"
"    border: 1px solid #333344;  /* Çok ince, belli belirsiz bir çerçeve */\n"
"}\n"
"\n"
"/* Üzerine gelince \"Ben buradayım\" desin */\n"
"QPushButton:hover {\n"
"    background-color: #333344;  /* Hafif aydınlansın */\n"
"    color: #FFFFFF;             /* Yazı beyazlaşsın */\n"
"}")
        self.pushButton_Otonom.setObjectName("pushButton_Otonom")
        self.verticalLayout_10.addWidget(self.pushButton_Otonom)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(15)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_aracBatarya = QtWidgets.QFrame(self.alt_bar)
        self.frame_aracBatarya.setMinimumSize(QtCore.QSize(150, 120))
        self.frame_aracBatarya.setMaximumSize(QtCore.QSize(150, 120))
        self.frame_aracBatarya.setStyleSheet("QFrame#frame_aracBatarya {\n"
"    background-color: transparent; /* İçi boş/şeffaf */\n"
"    border: 2px solid #0055FF;     /* Neon Mavi Çerçeve */\n"
"    border-radius: 16px;           /* Yuvarlak Köşe */\n"
"}")
        self.frame_aracBatarya.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_aracBatarya.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_aracBatarya.setObjectName("frame_aracBatarya")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_aracBatarya)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 15, 130, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_arac = QtWidgets.QLabel(self.layoutWidget1)
        self.label_arac.setEnabled(True)
        self.label_arac.setMinimumSize(QtCore.QSize(51, 21))
        self.label_arac.setStyleSheet("color: #0055FF; \n"
"font-weight: bold;\n"
"font-size: 26px; ")
        self.label_arac.setAlignment(QtCore.Qt.AlignCenter)
        self.label_arac.setObjectName("label_arac")
        self.verticalLayout_3.addWidget(self.label_arac)
        self.label_aracSarj = QtWidgets.QLabel(self.layoutWidget1)
        self.label_aracSarj.setMinimumSize(QtCore.QSize(128, 28))
        self.label_aracSarj.setStyleSheet("color: #FFFFFF;         /* Beyaz Yazı */\n"
"font-size: 26px;        /* Büyük Punto */\n"
"font-weight: bold;      /* Kalın */\n"
"background-color: transparent;")
        self.label_aracSarj.setTextFormat(QtCore.Qt.PlainText)
        self.label_aracSarj.setAlignment(QtCore.Qt.AlignCenter)
        self.label_aracSarj.setObjectName("label_aracSarj")
        self.verticalLayout_3.addWidget(self.label_aracSarj)
        self.verticalLayout_9.addWidget(self.frame_aracBatarya)
        self.frame_yerBatarya = QtWidgets.QFrame(self.alt_bar)
        self.frame_yerBatarya.setMinimumSize(QtCore.QSize(150, 110))
        self.frame_yerBatarya.setMaximumSize(QtCore.QSize(150, 120))
        self.frame_yerBatarya.setStyleSheet("QFrame#frame_yerBatarya {\n"
"    background-color: transparent; /* İçi boş/şeffaf */\n"
"    border: 2px solid #0055FF;     /* Neon Mavi Çerçeve */\n"
"    border-radius: 16px;           /* Yuvarlak Köşe */\n"
"}")
        self.frame_yerBatarya.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_yerBatarya.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_yerBatarya.setObjectName("frame_yerBatarya")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_yerBatarya)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 11, 131, 91))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_yer = QtWidgets.QLabel(self.layoutWidget2)
        self.label_yer.setMinimumSize(QtCore.QSize(51, 26))
        self.label_yer.setStyleSheet("color: #0055FF; \n"
"font-weight: bold;\n"
"font-size: 26px; ")
        self.label_yer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_yer.setObjectName("label_yer")
        self.verticalLayout_4.addWidget(self.label_yer)
        self.label_yerSarj = QtWidgets.QLabel(self.layoutWidget2)
        self.label_yerSarj.setMinimumSize(QtCore.QSize(51, 26))
        self.label_yerSarj.setStyleSheet("color: #FFFFFF;         /* Beyaz Yazı */\n"
"font-size: 26px;        /* Büyük Punto */\n"
"font-weight: bold;      /* Kalın */\n"
"background-color: transparent;")
        self.label_yerSarj.setTextFormat(QtCore.Qt.PlainText)
        self.label_yerSarj.setAlignment(QtCore.Qt.AlignCenter)
        self.label_yerSarj.setObjectName("label_yerSarj")
        self.verticalLayout_4.addWidget(self.label_yerSarj)
        self.verticalLayout_9.addWidget(self.frame_yerBatarya)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.alt_bar, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_6)
        self.gridLayout.addWidget(self.icerik_frame, 0, 1, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_baslik.setText(_translate("MainWindow", "TUFAN YER KONTROL İSTASYONU"))
        self.label_radar_cember.setText(_translate("MainWindow", "TextLabel"))
        self.label_sistemYazi.setText(_translate("MainWindow", "SİSTEM : HAZIR"))
        self.label_motorYazi.setText(_translate("MainWindow", "MOTORLAR : AKTİF"))
        self.label_GucYazi.setText(_translate("MainWindow", "GÜÇ SİSTEMİ : NORMAL"))
        self.label_lidarYazi.setText(_translate("MainWindow", "LIDAR : TARANIYOR"))
        self.label_wifiYazi.setText(_translate("MainWindow", "WIFI : %95"))
        self.label_gpsYazi.setText(_translate("MainWindow", "GPS : ETKİN"))
        self.label_kameraYazi.setText(_translate("MainWindow", "KAMERA : HAZIR"))
        self.pushButton_KAYIT.setText(_translate("MainWindow", "Veri Kaydet"))
        self.label_navigasyonYazi.setText(_translate("MainWindow", "NAVİGASYON VE GÖREV PLANLAMA"))
        self.label_sistemBilgisiVeLisans.setText(_translate("MainWindow", "SİSTEM BİLGİSİ VE LİSANS"))
        self.textBrowser_Bilgi.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:16px; font-weight:600; color:#00ff00;\">&gt; ANA BEYİN (EDGE AI):</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:16px; color:#a0c0d0;\"> NVIDIA Jetson (Otonom Sürüş &amp; Karar Mekanizması) </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:16px; font-weight:600; color:#00ff00;\">&gt; ALT SİSTEM KONTROL:</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:16px; color:#a0c0d0;\"> Arduino Mega 2560 (Gerçek Zamanlı I/O ve PWM Kontrolü) </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:16px; font-weight:600; color:#00ff00;\">&gt; HABERLEŞME PROTOKOLÜ:</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:16px; color:#a0c0d0;\"> </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:16px; font-weight:600; color:#a0c0d0;\">ROS 2 Humble</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:16px; color:#a0c0d0;\"> (DDS Middleware, Pub/Sub Mimarisi) &amp; Kriptolu 2.4 GHz Telemetri </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:16px; font-weight:600; color:#00ff00;\">&gt; GCS ALTYAPISI:</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:16px; color:#a0c0d0;\"> Python 3.12 | PyQt5 | Asenkron QThread Motoru </span></p>\n"
"<hr />\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:large; font-weight:600; color:#00ffff;\">[ SENSÖR FÜZYONU VE DURUM YÖNETİMİ ]</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:large; font-weight:600; color:#a0c0d0;\"> </span></h3>\n"
"<ul type=\"square\" style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'Courier New\',\'monospace\'; color:#00ff00;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px; font-weight:600; color:#e0e0e0;\">LİDAR ALTYAPISI:</span><span style=\" font-size:16px; color:#e0e0e0;\"> 360 Derece Çevresel Tarama, Haritalama (SLAM) ve Engel Algılama</span><span style=\" font-size:16px;\"> </span></li>\n"
"<li style=\" font-family:\'Courier New\',\'monospace\'; color:#00ff00;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px; font-weight:600; color:#e0e0e0;\">GÖRÜNTÜ İŞLEME:</span><span style=\" font-size:16px; color:#e0e0e0;\"> Düşük Gecikmeli (Low-Latency) Kamera Akışı ve Nesne Tespiti</span><span style=\" font-size:16px;\"> </span></li>\n"
"<li style=\" font-family:\'Courier New\',\'monospace\'; color:#00ff00;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px; font-weight:600; color:#e0e0e0;\">TELEMETRİ:</span><span style=\" font-size:16px; color:#e0e0e0;\"> 50ms Gecikme ile Canlı Durum Taraması ve Güvenlik Döngüsü (Fail-Safe)</span><span style=\" font-size:16px;\"> </span></li></ul>\n"
"<hr />\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:large; font-weight:600; color:#00ffff;\">[ TAKIM BİLGİSİ VE VİZYON ]</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:large; font-weight:600; color:#a0c0d0;\"> </span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:16px; font-weight:600; color:#00ff00;\">&gt; GÖREV GÜCÜ:</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:16px; color:#a0c0d0;\"> [Takım Adını Buraya Yazın] </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:16px; color:#e0e0e0;\">Teknofest 2026 İnsansız Kara Araçları (İKA) kategorisi için bir araya gelen ekibimiz; yazılım, elektronik ve mekanik disiplinlerini kusursuz bir uyumla birleştirmektedir. Amacımız, sadece yarışma parkurunu tamamlamak değil; </span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:16px; font-weight:600; color:#e0e0e0;\">&quot;Milli Teknoloji Hamlesi&quot;</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:16px; color:#e0e0e0;\"> vizyonu doğrultusunda, asimetrik harp koşullarında ve zorlu arazi şartlarında görev yapabilecek, yerli ve milli otonom sistemler için ölçeklenebilir bir Ar-Ge altyapısı sunmaktır. TUFAN, bu vizyonun sahadaki çelik yansımasıdır ve ROS 2 mimarisi ile gelecekteki sürü (swarm) operasyonlarına dahi bugünden hazırdır.</span><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:16px; color:#a0c0d0;\"> <br /></span></p>\n"
"<p align=\"right\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\',\'monospace\'; font-size:14px; font-weight:600; font-style:italic; color:#ff3333;\">&quot;Geleceğin harekat sahasında, kontrol daima güvendedir.&quot;</span></p></body></html>"))
        self.label_ayarlarYazi.setText(_translate("MainWindow", "SİSTEM AYARLARI "))
        self.label_genelAyarlarYazi.setText(_translate("MainWindow", "GENEL AYARLAR"))
        self.label_kontrolAyarlariYazi.setText(_translate("MainWindow", "KONTROL AYARLARI"))
        self.label_guvenlikKontrolleriYazi.setText(_translate("MainWindow", "GÜVENLİK KONTROLLERİ"))
        self.label_goruntuAyarlari.setText(_translate("MainWindow", "GÖRÜNTÜ AYARLARI"))
        self.label_veriYedeklemeYazi.setText(_translate("MainWindow", "VERİ YEDEKLEME"))
        self.label_sistemDili.setText(_translate("MainWindow", "S i s t e m   D i l i :"))
        self.comboBox_dilSecimi.setItemText(0, _translate("MainWindow", "Türkçe"))
        self.comboBox_dilSecimi.setItemText(1, _translate("MainWindow", "English"))
        self.comboBox_temaSecimi.setItemText(0, _translate("MainWindow", "Koyu Mod"))
        self.comboBox_temaSecimi.setItemText(1, _translate("MainWindow", "Açık Mod"))
        self.label_tema.setText(_translate("MainWindow", "T e m a :"))
        self.label_bildirimler.setText(_translate("MainWindow", "B i l d i r i m l e r :"))
        self.pushButton_bildirimler.setText(_translate("MainWindow", "Açık"))
        self.label_VPN.setText(_translate("MainWindow", "V P N :"))
        self.comboBox_VPNsecimi.setItemText(0, _translate("MainWindow", "VPN 1"))
        self.comboBox_VPNsecimi.setItemText(1, _translate("MainWindow", "VPN 2"))
        self.lineEdit_kullaniciAdi.setText(_translate("MainWindow", "Admin_Tufan"))
        self.label_kullaniciAdi.setText(_translate("MainWindow", "K u l l a n ı c ı   A d ı :"))
        self.label_sifre.setText(_translate("MainWindow", "Ş i f r e :"))
        self.lineEdit_sifre.setText(_translate("MainWindow", "Admin_Tufan"))
        self.label_telefon.setText(_translate("MainWindow", "T e l e f o n :"))
        self.label_canliSistemLog.setText(_translate("MainWindow", "CANLI SİSTEM LOGLARI :"))
        self.textEdit_canliSistemLog.setMarkdown(_translate("MainWindow", "**[14:22:01] Settings page accessed.  **\n"
"\n"
"**[14:22:05] User: Admin authorized.  **\n"
"\n"
"**[14:22:10] Security check: Pass.  **\n"
"\n"
"**[14:22:12] Backup service: Idle.**\n"
"\n"
""))
        self.textEdit_canliSistemLog.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto Mono\',\'Consolas\'; font-size:14px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\">[14:22:01] Settings page accessed.  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\">[14:22:05] User: Admin authorized.  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\">[14:22:10] Security check: Pass.  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\">[14:22:12] Backup service: Idle.</span></p></body></html>"))
        self.label_joystick.setText(_translate("MainWindow", "J o y s t i c k :"))
        self.pushButton_joystick.setText(_translate("MainWindow", "Bağlı"))
        self.label_klavyeKontrol.setText(_translate("MainWindow", "K l a v y e   K o n t r o l :"))
        self.pushButton_klavye.setText(_translate("MainWindow", "Pasif"))
        self.comboBox_yayinKalite.setItemText(0, _translate("MainWindow", "1080p - Yüksek"))
        self.comboBox_yayinKalite.setItemText(1, _translate("MainWindow", "720p - Orta"))
        self.comboBox_yayinKalite.setItemText(2, _translate("MainWindow", "480p - Düşük"))
        self.label_yayinKalite.setText(_translate("MainWindow", "Y a y ı n   K a l i t e s i :"))
        self.label_FPS.setText(_translate("MainWindow", "F P S   S ı n ı r ı :"))
        self.comboBox_FPS.setItemText(0, _translate("MainWindow", "60 Kare/sn"))
        self.comboBox_FPS.setItemText(1, _translate("MainWindow", "30 Kare/sn"))
        self.lineEdit_hedefKlasor.setText(_translate("MainWindow", "/home/tufan/rec"))
        self.label_hedefKlasor.setText(_translate("MainWindow", "H e d e f   K l a s ö r :"))
        self.label_sifreleme.setText(_translate("MainWindow", "Ş i f r e l e m e :"))
        self.pushButton_sifreleme.setText(_translate("MainWindow", "Açık"))
        self.pushButton_simdiYedekle.setText(_translate("MainWindow", "Ş i m d i   Y e d e k l e"))
        self.terminal_ekrani.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto Mono\'; font-size:5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:15px;\"><br /></p></body></html>"))
        self.label_hizYazi.setText(_translate("MainWindow", "<html><head/><body><p>2.4 m/s</p></body></html>"))
        self.pushButton_manuel.setText(_translate("MainWindow", "M A N U E L"))
        self.label_etap.setText(_translate("MainWindow", "<html><head/><body><p>E T A P</p></body></html>"))
        self.label_etapNo.setText(_translate("MainWindow", "<html><head/><body><p>8</p></body></html>"))
        self.pushButton_Otonom.setText(_translate("MainWindow", "O T O N O M"))
        self.label_arac.setText(_translate("MainWindow", "Araç ⚡️"))
        self.label_aracSarj.setText(_translate("MainWindow", "%100"))
        self.label_yer.setText(_translate("MainWindow", "Yer ⚡️"))
        self.label_yerSarj.setText(_translate("MainWindow", "%100"))
import kaynak_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
